accounts/urls.py
from __future__ import absolute_import

from django.conf.urls import patterns, include, url
from django.core.urlresolvers import reverse,resolve
from django.contrib.auth.decorators import login_required
from .models import *
from .views import *


urlpatterns = patterns('accounts.views',

    url(r'^login/$',LoginView.as_view(),
        name = 'login'),
        
    url(r'^logout/$','logout_view',name='logout'),
    
    #url(r'^lockout/$',AccountLockView.as_view(),name = 'lockout'),
        
      
    url(r'^signup$',RegistrationView.as_view(),
        name = 'signup'),
    
 
        
    url(r'^redirect/$',RegSuccessView.as_view(),
        name = 'redirect'),
        
    
    #url(r'^password/(?P<pk>\d+)/$',ChangePasswordFormView.as_view(),name='password'),
        
   

)

accounts/models.py
from __future__ import(
absolute_import, unicode_literals
) 


from django.db import models
from django.db.models import *
from django.contrib import auth
from django.conf import settings
from django.contrib.auth.models import *
from django.contrib.auth.signals import user_logged_in


from django.db.models.manager import EmptyManager
from django.utils.crypto import get_random_string
from django.utils.translation import ugettext_lazy as _
from tinymce.models import HTMLField

from kenstream.settings import *


class CustomUserManager(BaseUserManager):
    def create_user(self, phone_number, password=None, **extra_fields):
        now = timezone.now()
        if not phone_number:
            raise ValueError('The given phone number must be set')
        #email = UserManager.normalize_email(email)
        user = self.model(phone_number=phone_number,
                          is_staff=False,is_superuser=False,
                          last_login=now, date_joined=now, **extra_fields)
 
        user.set_password(password)
        user.save(using=self._db)
        return user
 
    def create_superuser(self, phone_number, password, **extra_fields):
        u = self.create_user(phone_number, password, **extra_fields)
        u.is_admin = True
        u.save(using=self._db)
        return u

# Users are going to eventually pay for the streaming service
# so we need a custom user model eventually
class CustomUser(AbstractBaseUser, PermissionsMixin):
    full_name = models.CharField(
       max_length=50,db_index=True,
       verbose_name='First & Last Name'
    )
    phone_number = models.CharField(
       max_length=15,unique=True,
       verbose_name='Phone Number'
    )
    photo = models.ImageField(
       upload_to='/images/profiles',
       verbose_name ='Profile Photo',
       null=True,blank=True
    )
    gender = models.CharField(
       max_length=1,choices=settings.GENDER,
       verbose_name='Select Gender',
       default=1
    )
    email = models.EmailField(
       max_length=100,null=True,
       verbose_name='E-mail Address',
       blank=True
    )
    description = HTMLField(
       max_length=350,null=True,blank=True,
       verbose_name='About Yourself'  
    )
    is_staff = models.BooleanField(
       default=False
    )
    #is_superuser = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)
    date_joined = models.DateTimeField(
       auto_now_add=True
    )
    USERNAME_FIELD = 'phone_number'
    REQUIRED_FIELDS = ['full_name',]
    
    objects = CustomUserManager()
    
    class Meta(object):
        db_table='CustomUser'
        ordering = ['date_joined']
        verbose_name_plural='CustomUsers'
        
    def __unicode__(self):
        return self.full_name
        
    
    
    def get_absolute_url(self):
        return "/users/%s/" % urlquote(self.full_name)
           
    def get_full_name(self):
        #the user is identified by their id_number
        return self.full_name
        
    def get_short_name(self):
        return self.full_name
        
    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin
        
   
    def save(self,*args,**kwargs):
        super(CustomUser,self).save(*args,**kwargs)
        

accounts/forms.py
from django import forms
from django.forms import *
from django import template
from django.forms.fields import *
from django.forms.widgets import *
from django.forms import ModelForm
from django.template import loader
from django.contrib.auth.models import User

from django.contrib.auth import authenticate, get_user_model
from django.contrib.auth.tokens import default_token_generator
from django.contrib.sites.models import get_current_site

from django.forms.util import ValidationError
from django.utils.translation import ugettext_lazy as _
from django.db.models.fields.files import *
from django.contrib.auth.forms import *
from django.core import validators
from form_utils.widgets import *
from form_utils.fields import *
from django.db.models import *


from kenstream.settings import *
from accounts.models import *
from .models import *

class BaseModelForm(ModelForm):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault('auto_id', '%s')
        kwargs.setdefault('label_suffix', '')
        super().__init__(*args, **kwargs)

        for field_name in self.fields:
            field = self.fields.get(field_name)
            if field:
                field.widget.attrs.update({
                    'placeholder': field.verbose_name
                })

attrs_dict = {'class': 'required'}

# see :http://stackoverflow.com/questions/4101258/how-do-i-add-a-placeholder-on-a-charfield-in-django

#widget=forms.TextInput(attrs={'placeholder': ''}) 

class UserCreationForm(forms.ModelForm):
    error_messages = {
        'duplicate_username': _("Phone Number already exists.")
    }
    password1 = forms.CharField(
       max_length=50,
       widget=forms.PasswordInput()
    )
    phone_number = forms.CharField(
       max_length=15
    )
    photo = forms.ImageField(
      widget=ImageWidget()
    )
    
    def __init__(self, *args, **kwargs):
        super(UserCreationForm, self).__init__(*args, **kwargs)
        self.fields['photo'].widget.attrs['class'] = 'fileUpoad'

       
        

    class Meta:
        model = get_user_model()
        fields = (
        "full_name","photo",
        "phone_number",
        )
        
      
           
    def clean_phone_number(self):
        phone_number = self.cleaned_data["phone_number"]
        try:
            get_user_model().objects.get(phone_number=phone_number)
        except get_user_model().DoesNotExist:
            return id_number
        raise forms.ValidationError("A user with that Phone Number already exists.")
    
    def clean_password1(self):
        password1 = self.cleaned_data.get("password1", "")
        if len(password1) == 0:
            raise forms.ValidationError("Please choose a password.")
        return password1
        
    def clean_full_name(self):
        full_name = self.cleaned_data['full_name']
        
        if len(full_name) > 50:
            raise ValidationError(_('Your name should not exceed 50 characters'))
        return full_name
        
    
    
          
    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


                
           
        
class MyUserChangeForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = CustomUser
      
                           

        
#widget=forms.TextInput(attrs={'placeholder': ''})   
               
class MyAuthForm(forms.Form):
    username = forms.CharField(
    max_length=254
    )
    password = forms.CharField(
    widget=forms.PasswordInput()
    ) 
    
    error_messages = {
        'invalid_login': _("Please enter a correct Phone Number and Password. "
                           ),
        'no_cookies': _("Your Web browser doesn't appear to have cookies "
                        "enabled. Cookies are required for logging in."),
        'inactive': _("This account is inactive."),
    }
   
    def __init__(self, request=None, *args, **kwargs):
        self.request = request
        self.user_cache = None
        super(MyAuthForm, self).__init__(*args, **kwargs)
    
            
   

        # Set the label for the "username" field.
        UserModel = get_user_model()
        

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if username and password:
            self.user_cache = authenticate(username=username,
                                           password=password)
            if self.user_cache is None:
                raise forms.ValidationError(
                    self.error_messages['invalid_login'])
            elif not self.user_cache.is_active:
                raise forms.ValidationError(self.error_messages['inactive'])
        self.check_for_test_cookie()
        return self.cleaned_data

    #throws errors:to be deleted
    def check_for_test_cookie(self):
        if self.request and not self.request.session.test_cookie_worked():
            raise forms.ValidationError(self.error_messages['no_cookies'])

    def get_user_id(self):
        if self.user_cache:
            return self.user_cache.id
        return None

    def get_user(self):
        return self.user_cache


               

    
class MyPasswordChangeForm(forms.Form):
    error_messages = {
        'password_mismatch': _("The two PINs  didn't match."),
    }
    old_password = forms.CharField(
       label=_("Current Password"),
       widget=forms.PasswordInput()
    )
    new_password1 = forms.CharField(
       label=_("New Password"),
       widget=forms.PasswordInput()
    )
    new_password2 = forms.CharField(
       label=_("Confirm Password"),
       widget=forms.PasswordInput()
    )
    
    
    def __init__(self, user=None, *args, **kwargs):
        self.user = user
        super(MyPasswordChangeForm, self).__init__(*args, **kwargs)
   
    def clean_old_password(self):
        UserModel = get_user_model()
        old_password = self.cleaned_data["old_password"]
        self.users_cache = UserModel._default_manager.filter(
        password__iexact=password
        )
        if not len(self.users_cache):
            raise forms.ValidationError(
                self.error_messages['pin_incorrect']
                )
    """  
    def clean_old_password(self):
        old_password = self.cleaned_data["old_password"]
        if not self.user.check_password(old_password):
                raise forms.ValidationError(
                self.error_messages['pin_incorrect'])
        #if self.old_password:
            #self.user_cache = authenticate(old_password)
            #if self.user_cache is None:
                raise forms.ValidationError(
                self.error_messages['pin_incorrect'])
        return old_password
    """ 
        
    def clean_password2(self):
        new_password1 = self.cleaned_data.get('new_password1')
        new_password2 = self.cleaned_data.get('new_password')
        if new_password1 and new_password2:
            if new_password1 != new_password2:
                raise forms.ValidationError(
                    self.error_messages['password_mismatch'])
        return new_password2

    def save(self, commit=True):
        self.user.set_password(self.cleaned_data["new_password1"])
        if commit:
            self.user.save()
        return self.user
        
            

accounts/templates/core.html
<!DOCTYPE html>

<html class="no-js" lang="en" manifest="">

<head> 

<!--[if lt IE 9]>
<script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="shortcut icon" href="{{MEDIA_URL}}img/favicon.ico">

                         <title>Kenstream</title>
      
                          {% block meta %}           
    <meta name="description" content="Kenstream is a simple movie recommendation forum">
                          {% endblock %}
    
         
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="keywords" content="Streaming,Movies,Series,Recommendations,Reviews,Documentaries,Kenyan">
    
     <!-- google settings -->
    
     <!-- bing settings --->
   
    
    
<!---styles --->



<!---
<link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
-->
<link href='http://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>


<link rel="stylesheet" href="{{MEDIA_URL}}css/main.css">
<link rel="stylesheet" href="{{MEDIA_URL}}material-design-iconic-font/css/material-design-iconic-font.min.css"> 

<!--- end styles --->
</head>

<body>
        
                  {% block header %}
                  <section class="navbar centerpiece">
                  
   <i class="md md-tv md-2x"></i> <i class="md-2x">Kenstream</i>

                  
                  </section>
                  {% endblock %}
                   
                   
                   {% block nav %}{% endblock %}
   
       
                   {% block notifications %} {% endblock %}


                   {% block content %} {% endblock %}
                   {% block content1 %} {% endblock %}
                   
                   {% block content2 %} {% endblock %}
                   
                   {% block content3 %} {% endblock %}
                   
                   {% block content4 %} {% endblock %}
                   
                   {% block content5 %} {% endblock %}
                   
                   {% block content6 %} {% endblock %}
                   
                   {% block content7 %} {% endblock %}
                   
                   {% block content8 %} {% endblock %}
                   
                   {% block content9 %} {% endblock %}
                   
                   {% block content10 %} {% endblock %}
                   
                         
                              {% block footer %}
                    <footer class="footer centerpiece">
                           
          <p class="handwritten">Taking the hustle out of watching a good movie</p>

                         <article class="bottom-nav">
<a class="item-spacing" href="{% url 'series' %}">Series</a>
<span class="dot">&middot;</span> <a class="item-spacing" href="{% url 'tv' %}"> T.V Guide </a><span class="dot">&middot;</span> <a class="item-spacing" href="{% url 'documentaries' %}"> Documentaries  </a> <span class="dot">&middot;</span> <a class="item-spacing" href="{% url 'classics' %}"> Classics  </a>
                                 </article>
                                 
                            <article class="action-button">
                <a  href="{% url 'login' %}"> Write a Review  </a> 
                                    </article>  
                   

                               </footer>
                              {% endblock %}
               

                              {% block js %}
                        
                              {% endblock %}


     


    </body>
</html>

accounts/templates/cover.html
                        {% extends "core.html" %}
                        
                           {% block nav %}
                         <nav class="nav centerpiece">
                           <ul>
	    
	  <li class="current"><a href="{% url 'watchlist' %}">WatchList</a></li>
	       <li><a href="{% url 'tv' %}">Movies</a></li>
	        <li><a href="{% url 'series' %}">Series</a></li>
	         <li><a href="{% url 'tv' %}">T.V Guide</a></li>
	         <li><a href="{% url 'classics' %}">Classics</a></li>
	         
     
                             </ul>
                                
                                
                                </nav>
                            {% endblock %}
                            
                           

accounts/templates/login.html
                             <div class="fieldWrapper">
              <span class="required">{{ form.username.errors }}</span>
                           <label for="id_username">
                    <span class="align-field"> Phone Number</span>
                               {{ form.username}} 
                                    </div>
                                    
                              <div class="fieldWrapper">
                 <span class="required">{{ form.password.errors }}</span>
                           <label for="id_password1"> 
             <span class="align-field">Password</span></label>
                               {{ form.password }} 
                                      </div>

accounts/templates/login_form.html
                     {% extends "cover.html" %}
              
	            
                       {% block content %}
                  <h3 class="centerpiece"> Login </h3>
			   <section>
             <article class="loginCard">
         <form class="pure-form "  action="." method="post">{% csrf_token %}
                  {{form.non_field_errors }}

    		 {% include "login.html" %}

     <input type="submit" class="button" name="submit" value="Login" id="submit" />
        </form>
          </article>
            
            
                        <article class="action-button centerpiece">
                    <a href="{% url 'signup' %}"> SignUp </a>
                           </article>
                           
                           </section>
                       
                       {% endblock %}

accounts/templates/m_login_form.html
                     {% extends "mobile_cover.html" %}
              
	            
                          {% block content %}
                 <h3 class="align-center spaced"> SignUp </h3>
			<section>
             <article class="loginCard">
        <form   action="." method="post" >{% csrf_token %}
                  {{form.non_field_errors }}

    		   {% include "login.html" %}

     <input type="submit" class="button" name="submit" value="Login" id="submit" />
        </form>
          </article>
          
               <article class="action-button centerpiece">
                    <a href="{% url 'signup' %}"> SignUp </a>
                           </article>
                           
                           </section>
        
                       {% endblock %}

accounts/templates/m_reg_success.html
                              {% extends "m_user_base.html" %}
                              
                                  
                                   {% block content %}
                          <section class="centerpiece">
                             
                               <h3>Registration Success</h3>
                      
                                      <article> 
                       <p class="">Welcome aboard</p>
                           <p>
              Thanks for signing up as reviewer, please <a href="{% url 'login' %}">login</a> 
              and start writing some reviews.
                           </p>
                                    </article>
                                    
                                   
                               </section>
                             
                              {% endblock %}

accounts/templates/m_registration_form.html
                   {% extends "mobile_cover.html" %}
              
	            
                         {% block content %}
                 <h3 class="align-center spaced"> Login </h3>
			    <section>
             <article class="loginCard">
    <form   action="." method="post" enctype="multipart/form-data" >{% csrf_token %}
                     {{form.non_field_errors }}

    		 {% include "registration.html" %}

     <input type="submit" class="button" name="submit" value="SignUp" id="submit" />
        </form>
           </article>
              <section>
                         {% endblock %}

accounts/templates/m_user_base.html
                           {% extends "mobile_core.html" %}

accounts/templates/mobile_core.html
<!DOCTYPE html>

<!-- markup for a polygot page: accomodate HTML & XHTML -->
<html id="Kenstream" xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en" manifest="" class="no-js">
<head> 
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="shortcut icon" href="{{MEDIA_URL}}img/favicon.ico">
	               <title>Kenstream</title>
        
        
    <meta name="description" content="Kenstream is a simple movie recommendation forum">
        
        <meta name="HandheldFriendly" content="True">
        <meta name="MobileOptimized" content="320">
        
<meta name="viewport" content="width=device-width, initial-scale=1, minimal-ui, user-scalable=no">

          <meta http-equiv="x-dns-prefetch-control" content="on">
          
          
                <meta http-equiv="cleartype" content="on">
    
          <!-- google settings -->
     
     <!-- bing settings --->
    
    
<meta name="viewport" 
content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
      
<meta http-equiv="Content-Type" content="application/xhtml+xml; charset=utf-8" />

<!--
<link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
--->

<link rel="Stylesheet" type="text/css" href="{{MEDIA_URL}}css/styles.css"/>
<link rel="stylesheet" href="{{MEDIA_URL}}material-design-iconic-font/css/material-design-iconic-font.min.css"> 

<!--[if IEMobile 7]>
<link rel="stylesheet" type="text/css" href="mobile.css"  href="mobile.css" media="screen"  />
<![endif]-->


</head>
   
 <body>

                     
              {% block  header %}
              <section class="navbar">
<i class="md-tv md-2x align-left"></i><a class="neutral" href="{% url 'create' %}" title="Write Review"><i class="md-add md-2x align-right"></i></a>

               </section>
              {% endblock %}
                       
         

		{% block nav %} {% endblock %}
	     {% block notifications %}  {% endblock %}

		{% block content %}  {% endblock %}



		 {% block content1 %}{% endblock %}


		 {% block content2 %}{% endblock %}


		 {% block content3 %}{% endblock %}


		 {% block content4 %}{% endblock %}


		 {% block content5 %}{% endblock %}
		 
		 {% block content6 %}{% endblock %}
		 
		 {% block content7 %}{% endblock %}

 
		           {% block footer %}
                        <footer class="footer">
                        
                        <article class="sticky-footer">
<a class="neutral-link align-left" href="{% url 'watchlist' %}"><i class="md-home md-2x"></i></a>
              <a class="neutral btm-1" href=""><i class="md-search md-2x"></i></a>
             <a class="neutral btm-2" href=""><i class="md-public md-2x"></i></a>
          <a class="neutral align-right" href=""><i class="md-person md-2x"></i></a>
                        </article>
                              
      <p class="handwritten centerpiece">Taking the hustle out of watching a good movie</p>
            
                      
                      
                                 
                         <article class="action-button">
                <a  href="{% url 'login' %}"> Write a Review  </a> 
                                </article>  
                                 
                              </footer>
                            {% endblock %}
                     
                          {% block js %}

 <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
        
  
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-mobile/1.4.5/jquery.mobile.min.js">
</script>
                               
                               {% endblock %}
        
    

</body>
</html>

accounts/templates/mobile_cover.html
                         {% extends "mobile_core.html" %}
                         
                                {% block nav %}
                             <section class="">
                          

                                 </section>
                                {% endblock %}

accounts/templates/reg_success.html
                          {% extends "user_base.html" %}
                               
                             {% block content %}
                          <section class="centerpiece">
                           
                          <h3>Registration Success </h3>
                      
                                    <article> 
                           <p class="">Welcome aboard</p>
                           <p>
              Thanks for signing up as reviewer, please <a href="{% url 'login' %}">login</a> 
              and start writing some reviews.
                           </p>
                                    </article>
                                    
                                   
                               </section>
                             
                              {% endblock %}

accounts/templates/registration.html
                            <div class="fieldWrapper">
<span class="required align-center">{{ form.full_name.errors }}</span>
             <label for="id_full_name" > 
        <span class="align-field" >First & Last Name</span>
        
                              {{ form.full_name}} 
                
                                     </div>
                                     
                            <div class="fieldWrapper">
              <span class="required">{{ form.phone_number.errors }}</span>
                             <label for="id_phone_number">
                 <span class="align-field"> Phone Number</span>
                              {{ form.phone_number}} 
                                    </div>
                      
                      <div class="fieldWrapper">
               <span class="required">{{ form.photo.errors }}</span>
		            <label for="id_photo"> 
                <span class="align-field">Profile Photo</span>
                                   </label>
               <span class="align-field" > {{ form.photo }}</span>
    			       </div>
    			       
    			       
    			 <div class="fieldWrapper">
                 <span class="required">{{ form.password1.errors }}</span>
                           <label for="id_password1"> 
             <span class="align-field">Choose Password</span></label>
                              {{ form.password1 }} 
                                      </div>

accounts/templates/registration_form.html
                   {% extends "cover.html" %}
              
	            
                    {% block content %}
            <h3 class="centerpiece"> SignUp </h3>
			<section>
             <article class="loginCard ">
<form class="pure-form"   action="." method="post" enctype="multipart/form-data" >
{% csrf_token %}
                  {{form.non_field_errors }}

    		 {% include "registration.html" %}

     <input type="submit" class="button" name="submit" value="SignUp" id="submit" />
        </form>
           </article>
             </section>
                       {% endblock %}

accounts/templates/user_base.html
                             {% extends "core.html" %}
                             
                             {% block nav %}
                         <nav class="nav centerpiece">
                           <ul>
	    <span class="logo align-left"> Kenstream </span>
	  <li class="current"><a href="{% url 'watchlist' %}">WatchList</a></li>
	       <li><a href="">My Reviews</a></li>
	        <li><a href="">Account</a></li>
	         
                             </ul>
                                
                                
                                </nav>
                            {% endblock %}