watchlist/urls.py
from __future__ import absolute_import

from django.conf.urls import patterns, include, url
from django.core.urlresolvers import reverse,resolve
from django.contrib.auth.decorators import login_required
from .models import *
from .forms import *
from .views import *


urlpatterns = patterns('watchlist.views',


    #url(r'^post/$',login_required(PostReviewWizard.as_view(BasicsForm,DetailsForm)),name='post'),
    
    #url(r'^create/$',login_required(PostReview.as_view()),name='create'),
    url(r'^create/$',PostReview.as_view(),name='create'),

    #url(r'^edit/(?P<slug>[a-zA-Z0-9-]+)$',login_required(EditReview.as_view()),name = 'edit'),
     
    url(r'^edit/(?P<slug>[a-zA-Z0-9-]+)$',EditReview.as_view(),name = 'edit'),
    
    url(r'^like/$', 'like', name='like'), 
      
    url(r'^watchlist/$',WatchListView.as_view(),
        name='watchlist'),
    
    url(r'^discover/$',DiscoverListView.as_view(),
        name='discover'),
           
    url(r'^movie/(?P<slug>[a-zA-Z0-9-]+)/$',WatchDetailView.as_view(),
        name='movie'),
        
    url(r'^delete/(?P<slug>[a-zA-Z0-9-]+)/$',login_required(DeleteReview.as_view()),
        name='delete'),
    
    url(r'^documentaries/$',DocumentariesListView.as_view(),
        name='documentaries'),
        
    url(r'^series/$',SeriesListView.as_view(),
        name='series'),
        
    url(r'^classics/$',ClassicsListView.as_view(),
        name='classics'),
    
    url(r'^tv/$',TvShowsListView.as_view(),
        name='tv'),
        
    #url(r'^genre/$',GenreListView.as_view(),name='genre'),
    
    #url(r'^/$',login_required(),name=''),
            
    #url(r'^/$',login_required(),name),
        
    
        
        
        
)

watchlist/models.py
import datetime
from decimal import *
from django.db import models
from django.db.models import *
from datetime import timedelta
from django.conf import settings
from django.db.models.query import QuerySet
from django.contrib.auth.models import *
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext_lazy as _
from django.utils.functional import cached_property
from django.utils.encoding import smart_unicode
from django.utils.text import slugify


from tinymce.models import HTMLField
from .fields import EmbedVideoField
from kenstream.settings import *
import secretballot


class Genre(models.Model):
    name = models.CharField(
       max_length=50,verbose_name='Name'
    )
    user = models.ForeignKey(
       settings.AUTH_USER_MODEL,
       related_name='admin'
    )
    class Meta(object):
        db_table = 'Genre'
        verbose_name_plural = 'Genres'
        
    def __unicode__(self):
        return self.name
        
        
    def save(self,*args,**kwargs):
        super(Genre,self).save(*args,**kwargs)
        
 
        
class Movie(models.Model):
    title = models.CharField(
       max_length=50,db_index=True,
       verbose_name = 'Title'
    )
    genre = models.ForeignKey(
       Genre,related_name='+',
       verbose_name='Select Genre'
    )
    poster = models.ImageField(
       upload_to='uploads/%Y/%m/%d',
       verbose_name='Poster',
       null=True,blank=True
    )
    embed_video = HTMLField(
       max_length=300,
       name='Embed Video / Trailer',
       null=True,blank=True
    )
    video = EmbedVideoField(
       verbose_name='Embed Video',
       null=True,blank=True
    )
    original_video = models.FileField(
       upload_to='.',
       verbose_name='Upload Video',
       null=True,blank=True
    )
    cast = HTMLField(
       max_length=140,verbose_name='Cast',
       null=True,blank=True
    )
    director = HTMLField(
       max_length=140,verbose_name='Director',
       null=True,blank=True 
    )
    review = HTMLField(
       max_length=350,verbose_name='Review',
       help_text='html content',
    )
    ratings = models.CharField(
       max_length=100,choices=settings.RATINGS,
       verbose_name='Content Ratings',
       default=1
    )
    views = models.IntegerField(default=0)
    enable_comments = models.BooleanField(default=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    editors_pick = models.BooleanField(default=False)
    edited_on = models.DateTimeField(auto_now=True)
    is_public = models.BooleanField(default=True)
    slug = models.SlugField(max_length=100)
    user = models.ForeignKey(
       settings.AUTH_USER_MODEL,
       related_name='+'
    )
    class Meta(object):
        db_table = 'Movie'
        verbose_name_plural = 'Movies'
        
    def __unicode__(self):
        return self.title
    
    @models.permalink
    def get_absolute_url(self):
        """
        return ('video_detail', (), { 
            'year': self.timestamp.strftime("%Y"),
            'month': self.timestamp.strftime("%b"),
            'day': self.timestamp.strftime("%d"), 
            'slug': self.slug 
        })  
        """
        pass 
        
    def save(self,*args,**kwargs):
        self.slug = slugify(self.title)
        super(Movie,self).save(*args,**kwargs)
 
secretballot.enable_voting_on(Movie)

class Like(models.Model):
    user = models.ManyToManyField(
       settings.AUTH_USER_MODEL,
       related_name='likes'
    )
    movie = models.ForeignKey(
       Movie,related_name='+',
       verbose_name='Movie'
    )
    total_likes = models.IntegerField(
       default=0,verbose_name='Total Likes'
    )
    created_at = models.DateTimeField(
       auto_now_add=True
    )
    class Meta(object):
        db_table = 'Like'
        verbose_name_plural = 'Likes'
        
    def __unicode__(self):
        return unicode(self.movie)
        
    def save(self,*args,**kwargs):
        super(Like,self).save(*args,**kwargs)
        
        
               

watchlist/forms.py
from django import forms
from django.forms import *
from django import template
from django.forms.fields import *
from django.forms.widgets import *
from django.forms import ModelForm
from django.template import loader
from django.contrib.auth.models import User

from django.forms.util import ValidationError
from django.utils.translation import ugettext_lazy as _
from django.core import validators
from django.db.models.fields.files import *
from tinymce.widgets import TinyMCE
from form_utils.widgets import *
from form_utils.fields import *
from django.db.models import *

from kenstream.settings import *
from accounts.models import *
from .models import *

# {% load thumbnail %}   
class SimpleForm(forms.ModelForm):
   poster = forms.ImageField(
      widget=ImageWidget()
   )
   review = forms.CharField(
       max_length=350,
       widget=forms.Textarea(attrs={'rows':10,'cols':5}),
   )
   
   def __init__(self, *args, **kwargs):
        super(SimpleForm, self).__init__(*args, **kwargs)
        self.fields['poster'].widget.attrs['class'] = 'fileUpoad'
        self.fields['genre'].widget.attrs['class'] = 'fileUpoad'
        self.fields['ratings'].widget.attrs['class'] = 'fileUpoad'
        
   class Meta(object):
       model = Movie
       fields = (
       'title','genre','poster',
       'review','ratings',#'embed_video'
       )
   
   def clean_poster(self):#set min-size
        poster = self.cleaned_data['poster']   
        if 'content-type' in poster:  #require image to be a certain scalable size
            main, sub = poster['content-type'].split('/')  
            if not (main == 'image' and sub in CONTENT_TYPES):  
                raise forms.ValidationError(u'Please use a JPEG, GIF or PNG image.') 
        else:
            return poster     


     
#works with an update view 

class BasicsForm(forms.ModelForm):
    pass 
    """
    def __init__(self, *args, **kwargs):
        super(BasicsForm, self).__init__(*args, **kwargs)
        self.fields['poster'].widget.attrs['class'] = 'fileUpoad'
        self.fields['genre'].widget.attrs['class'] = 'alt=choices'
        
    class Meta(object):
        model = Movie
        fields = (
        'title','genre','video',
        'poster'
        )
    """        
        
class DetailsForm(forms.ModelForm):
    pass 
    """
    review = forms.CharField(
       max_length=350,
       widget=AutoResizeTextarea()
    )
    rating = forms.CharField(
         widget=forms.RadioSelect(
         renderer=StarsRadioFieldRenderer, 
         attrs={'class':'star'}, 
         choices=RATING_CHOICES
         )
     )
    def __init__(self, *args, **kwargs):
        super(DetailsForm, self).__init__(*args, **kwargs)
        #self.fields[''].widget.attrs['class'] = ''
        
    class Meta(object):
        model = Movie
        fields = (
        'cast','review','director',
        'rating'
        )
        
    def clean_review(self):
        review = self.cleaned_data['review']
        if len(self.cleaned_data['review'])> 350:
           raise forms.ValidationError("Review must be less than 350 words")
        else:
            return review
    """           

watchlist/templates/comment_base.html
                              
                          <div class="fieldWrapper blank">
                           {{ form.content_type.errors }}
                    <label for="id_content_type"> content type</label>
                               {{ form.content_type }}
                                  </div>
                                  
                        <div class="fieldWrapper blank">
                           {{ form.object_pk.errors }}
                       <label for="id_object_pk"> object</label>
                             {{ form.object_pk }}
                                   </div>
    <div class="fieldWrapper blank">
        {{ form.timestamp.errors }}
        <label for="id_timestamp">timestamp </label>
        {{ form.timestamp }}
    </div>
    <div class="fieldWrapper blank">
        {{ form.security_hash.errors }}
        <label for="id_security_hash"> security hash </label>
        {{ form.security_hash }}
    </div>
    <div class="fieldWrapper blank">
        {{ form.email.errors }}
        <label for="id_email"> email </label>
        {{ form.email }}
    </div>
    <div class="fieldWrapper blank">
        {{ form.url.errors }}
        <label for="id_url">url</label>
        {{ form.url }}
    </div>
    <div class="fieldWrapper blank">
        {{ form.honeypot.errors }}
        <label for="id_honeypot">honeypot</label>
        {{ form.honeypot }}
    </div>
    
    <div class="fieldWrapper blank">
        {{ form.name.errors }}
<label  for="id_name"> your name:</label><br/>
 <span id="name">{{ form.name }}</span>
    </div>
    
                        <div id="comment"  class="fieldWrapper">
                         {{ form.comment.errors }}
<label  for="id_comment"><span class="align-field">Comment:</span></label><br/>
           <span class="align-field mobile-form" id="comment">{{ form.comment }}</span>
                                </div>
    
   

watchlist/templates/documentaries_list.html
                        {% extends "core.html" %}
                        
                             {% block nav %}
                         <nav class="nav centerpiece">
                           <ul>
	    
	     <li ><a href="{% url 'watchlist' %}">WatchList</a></li>
	      <li><a href="{% url 'discover' %}">Discover</a></li>
	        <li><a href="{% url 'series' %}">Series</a></li>
	         <li><a href="{% url 'tv' %}">T.V Guide</a></li>
	         <li><a href="{% url 'classics' %}">Classics</a></li>
	         
     
                             </ul>
                                
                                
                                </nav>
                            {% endblock %}
                            
                     
                       <!-- load movies as cards -->
                          {% block content %}
                  <h2 class="centerpiece"> What To Watch</h2>
                          
                         <section class="adjusted">
                            
                      {% for movie in movie_list %}
                          <div id="columns">
                            
		               <figure>
                      
      <article> <img src ="{{MEDIA_URL}}img/interstellar.jpg" alt="Movie Poster"/></article>
                               
                           <article class="centerpiece"> 
     <h2><a href="{% url 'movie' movie.slug  %}">{{movie.title|safe|title}}</a></h2> 
                              </article>
                    
                              <article class="review">
            {{movie.review|safe|linebreaks|truncatechars:140}}
 <a class="align-center" href="{% url 'movie' movie.slug %}">&rarr;</a>
 
 
                    <article class="centerpiece">
                <p> <b> By {{movie.user.full_name|title}}</b></p>
         <p class="micro-copy"> {{movie.timestamp|timesince}} ago</p>
   
                                </article>
                  
                               
                                 </figure>
                                   </div>
                                 {% endfor %}
                                  
                                  </section>
                                 {% endblock %}
                                 

watchlist/templates/m_classics_list.html
                     {% extends "mobile_cover.html" %}
                     
                     
                         {% block content %}
               <article class="simple-title">Classics</article>
                          
                          {% for movie in movie_list %}
                        
                            <div class="card">
                       
                               <article>
       <img class="miniPoster" src ="{{MEDIA_URL}}img/interstellar.jpg" alt="Movie Poster"/>
                              </article>
     
                                
                           <article class="movie-title">
     <a href="{% url 'movie' movie.slug  %}">{{movie.title|safe|title}}</a>
                                     </article> 
                            
                             
                    
                    
                              <article class="review">
          <p>
{{movie.review|safe|linebreaks|truncatechars:140}}<a  href="{% url 'movie' movie.slug %}">
&rarr;</a>
          </p>
                                </article>
                        
                        <article class="centerpiece"> 
                 <p> <b> By {{movie.user.full_name|title}}</a></p>
              <span class="tiny-print time ">{{movie.timestamp|timesince}} ago </span>
                                 </article>
                                 
                                 {% empty %}
                         <article class="floatingCard noReview">
             <img class="posterCard" src="{{MEDIA_URL}}img/interstellar.jpg">
                   <p class="handwritten padded"> No reviews posted yet </p>
                                 </article> 
                                 
                                 
                                  </div>
                                 {% endfor %}
                                 
                                  
                                {% endblock %}
                                
                                

watchlist/templates/m_genre_list.html
                     {% extends "mobile_cover.html" %}
                     
                     
                         {% block content %}
               <article class="simple-title">Genres</article>
                          
                          {% for movie in movie_list %}
                        
                            <div class="card">
                       
                               <article>
       <img class="miniPoster" src ="{{MEDIA_URL}}img/interstellar.jpg" alt="Movie Poster"/>
                              </article>
     
                                
                           <article class="movie-title">
     <a href="{% url 'movie' movie.slug  %}">{{movie.title|safe|title}}</a>
                                     </article> 
                            
                             
                    
                    
                              <article class="review">
          <p>
{{movie.review|safe|linebreaks|truncatechars:140}}<a  href="{% url 'movie' movie.slug %}">
&rarr;</a>
          </p>
                                </article>
                        
                        <article class="centerpiece"> 
                 <p> <b> By {{movie.user.full_name|title}}</a></p>
              <span class="tiny-print time ">{{movie.timestamp|timesince}} ago </span>
                                 </article>
                                 
                                 {% empty %}
                         <article class="floatingCard noReview">
             <img class="posterCard" src="{{MEDIA_URL}}img/interstellar.jpg">
                   <p class="handwritten padded"> No reviews posted yet </p>
                                 </article> 
                                 
                                 
                                  </div>
                                 {% endfor %}
                                 
                                  
                                {% endblock %}
                                
                                

watchlist/templates/m_movie_form.html
                {% extends "m_user_base.html" %}
              
	            
                    {% block content %}
                  <article class="simple-title">
			{% if movie %}
			Edit Review
			{% else %}
			Write a Review
			{% endif%}
                          </article>
                          <section>
             <article class="loginCard">
    <form   action="." method="post" enctype="multipart/form-data" >{% csrf_token %}
                  {{form.non_field_errors }}

    		   {% include "movie.html" %}

     <input type="submit" class="button" name="submit" value="Post Review" id="submit" />
        </form>
           </article>
             </section>
                       {% endblock %}

watchlist/templates/m_movie_list.html
                     {% extends "mobile_cover.html" %}
                     
                     
                         {% block content %}
               <article class="simple-title">Watch List</article>
                          
                          {% for movie in movie_list %}
                        
                            <div class="card">
                       
                               <article>
       <img class="miniPoster" src ="{{MEDIA_URL}}img/interstellar.jpg" alt="Movie Poster"/>
                              </article>
     
                                
                           <article class="movie-title">
     <a href="{% url 'movie' movie.slug  %}">{{movie.title|safe|title}}</a>
                                     </article> 
                            
                             
                    
                    
                              <article class="review">
          <p>
{{movie.review|safe|linebreaks|truncatechars:140}}<a  href="{% url 'movie' movie.slug %}">
&rarr;</a>
          </p>
                                </article>
                        
                        <article class="centerpiece"> 
                 <p> <b> By {{movie.user.full_name|title}}</a></p>
              <span class="tiny-print time ">{{movie.timestamp|timesince}} ago </span>
                                 </article>
                                  </div>
                                  
                                  {% empty %}
                         <article class="centerpiece">
             
                   <p class="handwritten"> No reviews posted yet </p>
                                 </article> 
                                 {% endfor %}
                                 
                                  
                                {% endblock %}
                                
                                

watchlist/templates/m_user_list.html
                     {% extends "mobile_cover.html" %}
                     
                     
                         {% block content %}
                <h2 class="centerpiece"> Discover </h2>
                          
                          {% for movie in movie_list %}
                        
                            <div class="card">
                       
                               <article>
       <img class="miniPoster" src ="{{movie.poster.url}}" alt="Movie Poster"/>
                              </article>
     
                                
                           <article class="centerpiece">
     <h1><a href="{% url 'movie' movie.slug  %}">{{movie.title|safe|title}}</a></h1>
                                     </article> 
                                     
                           <article class="ratings">
                              {{movie.ratings|title|safe}}
                              </article>
                            
                             
                    
                    
                              <article class="review">
          <p>
{{movie.review|safe|linebreaks|truncatechars:140}}<a  href="{% url 'movie' movie.slug %}">
&rarr;</a>
          </p>
                                </article>
                                
                            <article class="social-buzz">
                                 {% likes movie %}
                                   </article>
                        
                        <article class="centerpiece micro-copy"> 
                 <p> <b> By {{movie.user.full_name|title}}</a></p>
              
                                 </article>
                                 
                                 
                                  </div>
                                  
                                  {% empty %}
                         <article class="centerpiece">
             
                   <p class="handwritten"> No reviews posted yet </p>
                                 </article> 
                                 {% endfor %}
                                 
                                  
                                {% endblock %}
                                

watchlist/templates/m_wizard_form.html
{% extends "base.html" %}

                     {% block content %}
<p>Step {{ wizard.steps.current }} of {{ wizard.steps.count }}</p>
<form action="." method="post">{% csrf_token %}
<table>
{{ wizard.management_form }}
{% if wizard.form.forms %}
    {{ wizard.form.management_form }}
    {% for form in wizard.form.forms %}
        {{ form }}
    {% endfor %}
{% else %}
    {{ wizard.form }}
{% endif %}
{% if wizard.steps.prev %}
<button name="wizard_prev_step" value="{{ wizard.steps.first }}">{% trans "First step" %}</button>
<button name="wizard_prev_step" value="{{ wizard.steps.prev }}">{% trans "Prev step" %}</button>
{% endif %}
</table>
<input type="submit">
</form>
{% endblock %}

watchlist/templates/movie.html
                        
                  
                           
                             <div class="fieldWrapper">
           <span class="required align-center">{{ form.title.errors }}</span>
                        <label for="id_title" > 
            <span class="align-field" >Title</span>
                              {{ form.title}} 
                                   </div>
                                     
                            <div class="fieldWrapper">
              <span class="required">{{ form.genre.errors }}</span>
                             <label for="id_genre">
                 <span class="align-field"> Select Genre</span>
                <span class="align-field">{{ form.genre}} </span>
                                    </div>
                      
                      <div class="fieldWrapper">
               <span class="required">{{ form.poster.errors }}</span>
		            <label for="id_poster"> 
                <span class="align-field">Upload Poster</span>
                                   </label>
               <span class="align-field" > {{ form.poster}}</span>
    			       </div>
    			       
    			 
    			      <div class="fieldWrapper">
               <span class="required">{{ form.ratings.errors }}</span>
		            <label for="id_ratings"> 
                <span class="align-field"> Rate Movie </span>
                                   </label>
               <span class="align-field" > {{ form.ratings}}</span>
    			       </div> 
    			 
                            
                            <div class="fieldWrapper">
                 <span class="required">{{ form.review.errors }}</span>
                           <label for="id_review"> 
             <span class="align-field">Write Review</span></label>
                                {{ form.review }} 
                                      </div>



    

watchlist/templates/movie_base.html
                     <fieldset class="pure-group">
    <input type="text" class="pure-input-1-2"  id="id_" placeholder="">
     <input type="text" class="pure-input-1-2"  id="id_" placeholder="">
     <input type="text" class="pure-input-1-2"  id="id_" placeholder="">
     <input type="text" class="pure-input-1-2"  id="id_" placeholder="">
     <input type="text" class="pure-input-1-2"  id="id_" placeholder="">
     <input type="text" class="pure-input-1-2"  id="id_" placeholder="">
     <input type="text" class="pure-input-1-2"  id="id_" placeholder="">
     <input type="text" class="pure-input-1-2"  id="id_" placeholder="">
                           </fieldset>

watchlist/templates/search_form.html
 
                            <article class="searchForm">
                            
                         <form action="/search/" method="get">
                          <input type="text" name="q">
                         <input type="submit" value="Search">
                                        </form>
                                        </article>

watchlist/templates/series_list.html
                        {% extends "core.html" %}
                        
                             {% block nav %}
                         <nav class="nav centerpiece">
                           <ul>
	    
	          <li ><a href="{% url 'watchlist' %}">WatchList</a></li>
	        <li class="current"><a href="{% url 'series' %}">Series</a></li>
	         <li><a href="{% url 'tv' %}">T.V Guide</a></li>
	         <li><a href="{% url 'classics' %}">Classics</a></li>
	         
     
                             </ul>
                                
                                
                                </nav>
                            {% endblock %}
                            
                     
                       <!-- load movies as cards -->
                          {% block content %}
                  <h2 class="centerpiece"> What To Watch</h2>
                          
                         <section class="adjusted">
                            
                      {% for movie in movie_list %}
                          <div id="columns">
                            
		               <figure>
                      
      <article> <img src ="{{MEDIA_URL}}img/interstellar.jpg" alt="Movie Poster"/></article>
                               
                           <article class="centerpiece"> 
     <h2><a href="{% url 'movie' movie.slug  %}">{{movie.title|safe|title}}</a></h2> 
                              </article>
                    
                              <article class="review">
            {{movie.review|safe|linebreaks|truncatechars:140}}
 <a class="align-center" href="{% url 'movie' movie.slug %}">&rarr;</a>
 
 
                    <article class="centerpiece">
                <p> <b> By {{movie.user.full_name|title}}</b></p>
         <p class="micro-copy"> {{movie.timestamp|timesince}} ago</p>
   
                                </article>
                                
                                 {% empty %}
                         <article class="floatingCard noReview">
             <img class="posterCard" src="{{MEDIA_URL}}img/interstellar.jpg">
                   <p class="handwritten padded"> No reviews posted yet </p>
                                 </article> 
                  
                               
                                 </figure>
                                   </div>
                                 {% endfor %}
                                  
                                  </section>
                                 {% endblock %}
                                 

watchlist/templates/tvshows_list.html
                        {% extends "core.html" %}
                        {% load likes_inclusion_tags %}
                        
                             {% block nav %}
                         <nav class="nav centerpiece">
                           <ul>
	    
	        <li ><a href="{% url 'watchlist' %}">WatchList</a></li>
	         <li><a href="{% url 'discover' %}">Discover</a></li>
	            <li><a href="{% url 'series' %}">Series</a></li>
	         <li class="current"><a href="{% url 'tv' %}">T.V Guide</a></li>
	         
	         
     
                             </ul>
                                
                                
                                </nav>
                            {% endblock %}
                            
                     
                       {% block content %}
                  <h2 class="centerpiece"> T.V Guide </h2>
                          
                         <section class="adjusted">
                            
                      {% for movie in movie_list %}
                          <div id="columns">
                            
		               <figure>
                      
      <article> <img src ="{{movie.poster.url}}" alt="Movie Poster"/></article>
                               
                           <article class="centerpiece"> 
     <h1><a href="{% url 'movie' movie.slug  %}">{{movie.title|safe|title}}</a></h1> 
                              </article>
                              
                         <article class="ratings">
                              {{movie.ratings|title|safe}}
                              </article>
                    
                              <article class="review">
            {{movie.review|safe|linebreaks|truncatechars:140}}
 <a class="align-center" href="{% url 'movie' movie.slug %}">&rarr;</a>
 
                                     </article>
                                     
                                <article class="social-buzz">
                                 {% likes movie %}
                                   </article>
 
 
                          <article class="centerpiece micro-copy">
                <p> <b> By {{movie.user.full_name|title}}</b></p>
                   
   
                                </article>
                  
                               
                                 </figure>
                                   </div>
                                 {% endfor %}
                                    
                                  </section>
                                 {% endblock %}
                                 